### ISSUE TITLE
the isTablet value is false, but the isDesktop is true when using safari on ipad pro

### ISSUE THREAD

**Issue by PingZi818** [nuxt-modules/device#153]

**Comment by renegadevi** [comment]
If you use Safari on your iPad Pro it will detect as Desktop, but if you use another browser such as Google Chrome it will detect as Tablet. 

This was done on purpose by Apple because users had demanded the browser on the 12.9" iPad Pro to be treated as desktop instead of several websites still used a more limited mobile site. In 2018 with the iPad Pro redesign, they made Safari act and detect the same as on the desktop.

As long something is read by a user agent, it's how it will be detected.
